site_name: 'ğŸº: `fil`: Read/write JSON/TOML/Yaml/txt ğŸº'

theme:
  name: material

  palette:
    primary:
      'cyan'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
